/**
 * Status Effect Visualizer — Generated by /vib3-create skill
 *
 * Maps game status effects to VIB3+ parameter presets.
 * Each effect = one atomic batch_set_parameters call.
 *
 * Usage:
 *   import { StatusEffects, applyEffect } from './status-effects.js';
 *   applyEffect(engine, 'poison');
 *   applyEffect(engine, 'freeze');
 *   applyEffect(engine, 'clear');  // Remove all effects
 */

export const StatusEffects = {
    poison: {
        name: 'Poison',
        description: 'Toxic green fractal dissolution on hypersphere',
        batch_set_parameters: {
            system: 'quantum',
            geometry: 13,   // hypersphere + fractal
            rotation: { XW: 0.8, YW: 0.3, ZW: 0.5 },
            visual: {
                hue: 120,           // green
                saturation: 0.9,
                chaos: 0.6,
                speed: 1.5,
                morphFactor: 1.2,
                intensity: 0.7,
                gridDensity: 35,
                dimension: 3.4
            }
        },
        rarity_contribution: 3.6  // extremity score
    },

    freeze: {
        name: 'Freeze',
        description: 'Pristine ice-blue crystalline lattice, near-frozen',
        batch_set_parameters: {
            system: 'faceted',
            geometry: 15,   // hypersphere + crystal
            rotation: { XW: 0.1, YW: 0.0, ZW: 0.05 },
            visual: {
                hue: 200,           // ice blue
                saturation: 0.5,
                chaos: 0.0,
                speed: 0.1,
                morphFactor: 0.0,
                intensity: 0.8,
                gridDensity: 80,
                dimension: 3.8
            }
        },
        rarity_contribution: 0.6  // low extremity
    },

    fire: {
        name: 'Fire',
        description: 'Volatile orange fractal combustion, maximum energy',
        batch_set_parameters: {
            system: 'quantum',
            geometry: 5,    // base fractal
            rotation: { XW: 1.5, YW: 0.8, ZW: 1.2 },
            visual: {
                hue: 15,            // orange
                saturation: 1.0,
                chaos: 0.8,
                speed: 2.5,
                morphFactor: 0.8,
                intensity: 0.9,
                gridDensity: 30,
                dimension: 3.5
            }
        },
        rarity_contribution: 5.3  // high extremity
    },

    shield: {
        name: 'Shield',
        description: 'Stable purple holographic sphere with dramatic depth',
        batch_set_parameters: {
            system: 'holographic',
            geometry: 10,   // hypersphere + sphere
            rotation: { XW: 0.2, YW: 0.15, ZW: 0.1 },
            visual: {
                hue: 270,           // purple
                saturation: 0.7,
                chaos: 0.05,
                speed: 0.3,
                morphFactor: 0.1,
                intensity: 0.6,
                gridDensity: 20,
                dimension: 3.2
            }
        },
        rarity_contribution: 1.05  // low-moderate
    },

    haste: {
        name: 'Haste',
        description: 'Rapid yellow wave patterns, maximum velocity',
        batch_set_parameters: {
            system: 'faceted',
            geometry: 6,    // base wave
            rotation: { XW: 0.5, YW: 1.0, ZW: 0.3 },
            visual: {
                hue: 60,            // yellow
                saturation: 0.8,
                chaos: 0.3,
                speed: 3.0,
                morphFactor: 0.5,
                intensity: 0.85,
                gridDensity: 15,
                dimension: 3.6
            }
        },
        rarity_contribution: 2.0
    },

    void: {
        name: 'Void',
        description: 'Deep purple hypertetra Klein bottle, maximum distortion fish-eye',
        batch_set_parameters: {
            system: 'quantum',
            geometry: 20,   // hypertetra + klein bottle
            rotation: { XW: 2.5, YW: 1.8, ZW: 2.0 },
            visual: {
                hue: 280,           // deep purple
                saturation: 0.6,
                chaos: 0.9,
                speed: 0.5,
                morphFactor: 1.8,
                intensity: 0.3,
                gridDensity: 50,
                dimension: 3.0
            }
        },
        rarity_contribution: 9.1  // MYTHIC extremity
    },

    rage: {
        name: 'Rage',
        description: 'Blood-red hypertetra crystal lattice, pulsing aggression',
        batch_set_parameters: {
            system: 'quantum',
            geometry: 23,   // hypertetra + crystal
            rotation: { XW: 1.8, YW: 1.2, ZW: 2.5 },
            visual: {
                hue: 355,           // blood red
                saturation: 1.0,
                chaos: 0.7,
                speed: 2.2,
                morphFactor: 1.5,
                intensity: 0.95,
                gridDensity: 45,
                dimension: 3.2
            }
        },
        rarity_contribution: 7.3  // LEGENDARY
    },

    heal: {
        name: 'Heal',
        description: 'Gentle green holographic sphere, breathing rhythm',
        batch_set_parameters: {
            system: 'holographic',
            geometry: 10,   // hypersphere + sphere
            rotation: { XW: 0.3, YW: 0.2, ZW: 0.15 },
            visual: {
                hue: 140,           // healing green
                saturation: 0.6,
                chaos: 0.02,
                speed: 0.4,
                morphFactor: 0.2,
                intensity: 0.7,
                gridDensity: 18,
                dimension: 3.8
            }
        },
        rarity_contribution: 0.85
    },

    clear: {
        name: 'Clear',
        description: 'Neutral state — no active effect',
        batch_set_parameters: {
            system: 'faceted',
            geometry: 2,    // base sphere
            rotation: { XW: 0.0, YW: 0.0, ZW: 0.0 },
            visual: {
                hue: 200,
                saturation: 0.5,
                chaos: 0.0,
                speed: 0.5,
                morphFactor: 0.0,
                intensity: 0.5,
                gridDensity: 20,
                dimension: 3.8
            }
        },
        rarity_contribution: 0.2
    }
};

/**
 * Apply a status effect to a VIB3Engine instance.
 * @param {Object} engine - VIB3Engine instance
 * @param {string} effectName - Key from StatusEffects
 * @param {number} [transitionMs=300] - Transition duration (0 for instant)
 */
export function applyEffect(engine, effectName, transitionMs = 300) {
    const effect = StatusEffects[effectName];
    if (!effect) {
        console.warn(`Unknown status effect: ${effectName}`);
        return;
    }

    const { system, geometry, rotation, visual } = effect.batch_set_parameters;

    if (transitionMs > 0 && engine.transition) {
        // Smooth transition to new effect state
        const targetParams = { ...visual };
        for (const [plane, value] of Object.entries(rotation)) {
            targetParams[`rot4d${plane}`] = value;
        }
        engine.switchSystem(system);
        engine.setParameter('geometry', geometry);
        engine.transition.play([{
            params: targetParams,
            duration: transitionMs,
            easing: 'easeInOut'
        }]);
    } else {
        // Instant application
        engine.switchSystem(system);
        engine.setParameter('geometry', geometry);
        for (const [plane, value] of Object.entries(rotation)) {
            engine.setParameter(`rot4d${plane}`, value);
        }
        for (const [param, value] of Object.entries(visual)) {
            engine.setParameter(param, value);
        }
    }
}

/**
 * Get rarity tier for a status effect (for trading card integration).
 * Uses same extremity formula as TradingCardGenerator.
 */
export function getEffectRarity(effectName) {
    const e = StatusEffects[effectName]?.rarity_contribution ?? 0;
    if (e > 8) return 'MYTHIC';
    if (e > 6) return 'LEGENDARY';
    if (e > 4) return 'EPIC';
    if (e > 2) return 'RARE';
    return 'COMMON';
}

// Quick summary
export const EFFECT_SUMMARY = Object.entries(StatusEffects).map(([key, val]) => ({
    name: val.name,
    key,
    system: val.batch_set_parameters.system,
    geometry: val.batch_set_parameters.geometry,
    hue: val.batch_set_parameters.visual.hue,
    rarity: getEffectRarity(key)
}));
