#!/usr/bin/env node
/**
 * VIB3+ Visual Catalog — Grid Compositor
 *
 * Reads screenshots from visual-catalog/output/ and composites them into
 * grid reference sheets for AI agent context. Uses HTML Canvas via Playwright.
 *
 * Usage:
 *   node tools/visual-catalog/composite.js
 *
 * Requires: visual-catalog/output/grids/grid-manifest.json (generated by capture.js)
 */

import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../..');
const OUTPUT = join(ROOT, 'visual-catalog', 'output');
const GRIDS_DIR = join(OUTPUT, 'grids');

const THUMB_W = 200;
const THUMB_H = 150;
const LABEL_H = 24;
const PAD = 4;

async function main() {
  const manifestPath = join(GRIDS_DIR, 'grid-manifest.json');
  if (!existsSync(manifestPath)) {
    console.error('Run capture.js first to generate the grid manifest');
    process.exit(1);
  }

  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();

  // Compose system grids (6 cols x 4 rows = 24 geometries)
  for (const grid of manifest.systems) {
    const [cols, rows] = grid.grid.split('x').map(Number);
    const w = cols * (THUMB_W + PAD) + PAD;
    const h = rows * (THUMB_H + LABEL_H + PAD) + PAD;

    const page = await context.newPage({ viewport: { width: w, height: h } });

    // Build HTML grid
    const images = grid.images.map((imgPath, i) => {
      const geoIdx = i;
      const geoName = [
        'Tetrahedron', 'Hypercube', 'Sphere', 'Torus',
        'Klein Bottle', 'Fractal', 'Wave', 'Crystal',
        'H-Tetra', 'H-Cube', 'H-Sphere', 'H-Torus',
        'H-Klein', 'H-Fractal', 'H-Wave', 'H-Crystal',
        'HT-Tetra', 'HT-Cube', 'HT-Sphere', 'HT-Torus',
        'HT-Klein', 'HT-Fractal', 'HT-Wave', 'HT-Crystal',
      ][geoIdx] || `Geo ${geoIdx}`;
      const fullPath = join(OUTPUT, imgPath);
      const b64 = existsSync(fullPath)
        ? `data:image/png;base64,${readFileSync(fullPath).toString('base64')}`
        : '';
      return `<div class="cell">
        <img src="${b64}" width="${THUMB_W}" height="${THUMB_H}">
        <div class="label">${geoIdx}: ${geoName}</div>
      </div>`;
    });

    const html = `<!DOCTYPE html><html><head><style>
      body { margin:0; background:#0a0a14; font-family:monospace; }
      .grid { display:grid; grid-template-columns:repeat(${cols}, ${THUMB_W + PAD}px); gap:${PAD}px; padding:${PAD}px; }
      .cell { text-align:center; }
      .cell img { border-radius:6px; border:1px solid rgba(0,240,255,0.2); display:block; }
      .label { color:rgba(255,255,255,0.7); font-size:10px; height:${LABEL_H}px; line-height:${LABEL_H}px; }
      h3 { color:#00f0ff; text-align:center; margin:8px 0 4px; font-size:14px; letter-spacing:2px; }
    </style></head><body>
    <h3>${grid.name.toUpperCase().replace(/-/g, ' ')}</h3>
    <div class="grid">${images.join('')}</div>
    </body></html>`;

    await page.setContent(html, { waitUntil: 'load' });
    await page.waitForTimeout(500);

    const outPath = join(GRIDS_DIR, `${grid.name}.png`);
    await page.screenshot({ path: outPath, fullPage: true });
    console.log(`Composited: ${grid.name}.png (${cols}x${rows})`);
    await page.close();
  }

  // Compose parameter effect strips
  for (const paramGrid of manifest.params) {
    const numImages = paramGrid.images.length;
    const w = numImages * (THUMB_W + PAD) + PAD;
    const h = THUMB_H + LABEL_H + PAD * 2 + 30;

    const page = await context.newPage({ viewport: { width: w, height: h } });

    const images = paramGrid.images.map((imgPath, i) => {
      const fullPath = join(OUTPUT, imgPath);
      const b64 = existsSync(fullPath)
        ? `data:image/png;base64,${readFileSync(fullPath).toString('base64')}`
        : '';
      const paramName = paramGrid.name.replace('param-', '').replace('-effect', '');
      // Extract value from filename
      const match = imgPath.match(/[\d_]+\.png$/);
      const valStr = match ? match[0].replace('.png', '').replace(/_/g, '.') : `${i}`;
      return `<div class="cell">
        <img src="${b64}" width="${THUMB_W}" height="${THUMB_H}">
        <div class="label">${paramName}=${valStr}</div>
      </div>`;
    });

    const html = `<!DOCTYPE html><html><head><style>
      body { margin:0; background:#0a0a14; font-family:monospace; }
      .strip { display:flex; gap:${PAD}px; padding:${PAD}px; }
      .cell { text-align:center; }
      .cell img { border-radius:6px; border:1px solid rgba(168,85,247,0.3); display:block; }
      .label { color:rgba(255,255,255,0.7); font-size:10px; height:${LABEL_H}px; line-height:${LABEL_H}px; }
      h3 { color:#a855f7; text-align:center; margin:8px 0 4px; font-size:13px; letter-spacing:2px; }
    </style></head><body>
    <h3>${paramGrid.name.toUpperCase().replace(/-/g, ' ')}</h3>
    <div class="strip">${images.join('')}</div>
    </body></html>`;

    await page.setContent(html, { waitUntil: 'load' });
    await page.waitForTimeout(300);

    const outPath = join(GRIDS_DIR, `${paramGrid.name}.png`);
    await page.screenshot({ path: outPath, fullPage: true });
    console.log(`Composited: ${paramGrid.name}.png (${numImages} images)`);
    await page.close();
  }

  await browser.close();
  console.log('\nAll grids composited.');
}

main().catch(e => { console.error(e); process.exit(1); });
